### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#20]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar el logo junto con el nombre.

## Resultado actual

• Se encuentra el nombre, pero no el logo.

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/e28bcebd-f1d3-4938-8254-ba20785af7e1)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
realizado
