### ISSUE TITLE
Reservas mesas

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#21]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una reserva.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre del cliente.
• Que no se permita reservas fechas anteriores a la fecha actual.
• Que se encuentre un horario apto para hacer la reserva.

## Resultado actual

• Se permite colocar numeros y signos en el nombre y apellido.
• Se permite colocar cualquier fecha para hacer la reserva.
• Se puede reservar cualquier hora. Ej: se puede reservar a las 5 de la mañana.

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/5c483e42-2807-4f70-bb00-cbfe694af3d1)
![image](https://github.com/ftarulli/fd-git/assets/166792979/f333e5de-4905-4f83-a2da-43c6ee3491ec)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
Resuelto
