### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#22]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que no se encuentre scroll horizontal.

## Resultado actual

• Se encuentra un scroll horizontal en la seccion de "registro" e "iniciar sesion".

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/7301131d-b0cf-4219-82d9-623123fccf5e)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
Se eliminaron todas las barras de scroll de todas las paginas
