### ISSUE TITLE
Botones sin accion.

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#23]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Que las flechitas funcionen para cambiar de imagen.

## Resultado actual

• Las flechitas no cumplen ninguna funcion.

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/a787a8c5-c0c4-4b94-ba82-606531573d15)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
Se eliminaron flechas
