### ISSUE TITLE
Registro

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#24]
## Proceso

1. Ingrese a la pagina.
2. Me dirigí a la seccion de registro.

## Resultado esperado

• Que todo se encuentre correctamente.

## Resultado actual

• Se encuentra texto fuera de lugar.

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/36c403f7-d7f9-4ee1-872a-59cedb514bc6)
Deberia quedar al igual que en la seccion de inicio de sesion.
![image](https://github.com/ftarulli/fd-git/assets/166792979/2a7907ef-99bd-43eb-a349-8baf27b15539)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
Hola nico, aca te envio lo mismo que te envie por slack. por aca se ve bien, igual hice ahi unos cambios a ver si en tu dispositivo si se ve bien. avisame

**Comment by VaniiB** [comment]
![registro ok](https://github.com/ftarulli/fd-git/assets/116386542/8b70b4e3-4ab3-43b2-aecd-c4d63a2bc2b7)
![registro okk](https://github.com/ftarulli/fd-git/assets/116386542/7ca8add3-518e-41b2-aad9-ca7b81abfd68)
