### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by NicoGonzalez94** [ftarulli/fd-git#25]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un nuevo usuario.

## Resultado esperado

• Que no se permita colocar numero ni signo en el nombre y apellido del usuario.

## Resultado actual

• Se permite colocar numeros y signos en el nombre y apellido del usuario.

## Captura

![image](https://github.com/ftarulli/fd-git/assets/166792979/5a6185f3-dc84-4800-b35e-5bcbe369c43b)
![image](https://github.com/ftarulli/fd-git/assets/166792979/9f63d9f4-efdb-48dd-a7cd-7dfaf5bcd859)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by VaniiB** [comment]
Resuelto
